In [19]:
import pandas as pd
import json
from nba_py import player

In [3]:
# Read in JSON file holding 2016-2017 NBA salaries

total_df = pd.read_json('2016_2017_salaries.json')
total_df

                      player    salary team_abbrev        team_name  team_rank
0              DeMar DeRozan  26540100         TOR  Toronto Raptors          1
1          Jonas Valanciunas  14382022         TOR  Toronto Raptors          2
10             Bruno Caboclo   1589640         TOR  Toronto Raptors         11
100          Anthony Bennett   1015696         BRK    Brooklyn Nets         16
101               Joe Harris    980431         BRK    Brooklyn Nets         17
102          Sean Kilpatrick    980431         BRK    Brooklyn Nets         18
103        Spencer Dinwiddie    726672         BRK    Brooklyn Nets         19
104             Jarrett Jack    500000         BRK    Brooklyn Nets         20
105          Andrea Bargnani    323599         BRK    Brooklyn Nets         21
106             Yogi Ferrell    202300         BRK    Brooklyn Nets         22
107           Archie Goodwin    194494         BRK    Brooklyn Nets         23
108     Egidijus Mockevicius    100000         BRK    Brooklyn Nets         24
109          Cliff Alexander     51449         BRK    Brooklyn Nets         25
11              Delon Wright   1577280         TOR  Toronto Raptors         12
110               Beau Beech     45000         BRK    Brooklyn Nets         26
111              Prince Ibeh     31969         BRK    Brooklyn Nets         27
112              Paul George  18314532         IND   Indiana Pacers          1
113           Thaddeus Young  14153652         IND   Indiana Pacers          2
114              Monta Ellis  10770000         IND   Indiana Pacers          3
115             Al Jefferson  10230179         IND   Indiana Pacers          4
116              Jeff Teague   8800000         IND   Indiana Pacers          5
117           Rodney Stuckey   7000000         IND   Indiana Pacers          6
118               C.J. Miles   4583450         IND   Indiana Pacers          7
119         Lance Stephenson   4000000         IND   Indiana Pacers          8
12             Pascal Siakam   1196040         TOR  Toronto Raptors         13
120              Lavoy Allen   4000000         IND   Indiana Pacers          9
121             Aaron Brooks   2700000         IND   Indiana Pacers         10
122             Myles Turner   2463840         IND   Indiana Pacers         11
123           Kevin Seraphin   1800000         IND   Indiana Pacers         12
124             Jeremy Evans   1227286         IND   Indiana Pacers         13
..                       ...       ...         ...              ...        ...
72              Jaylen Brown   4743000         BOS   Boston Celtics          8
73              Marcus Smart   3578880         BOS   Boston Celtics          9
74              Kelly Olynyk   3094014         BOS   Boston Celtics         10
75              Terry Rozier   1906440         BOS   Boston Celtics         11
76               James Young   1825200         BOS   Boston Celtics         12
77         Demetrius Jackson   1450000         BOS   Boston Celtics         13
78              Gerald Green   1410598         BOS   Boston Celtics         14
79             Jordan Mickey   1223653         BOS   Boston Celtics         15
8               Jakob Poeltl   2703960         TOR  Toronto Raptors          9
80               R.J. Hunter   1200240         BOS   Boston Celtics         16
81                Ben Bentil    250000         BOS   Boston Celtics         17
82                Damion Lee     50000         BOS   Boston Celtics         18
83               Jalen Jones     25000         BOS   Boston Celtics         19
84       Marcus Georges-Hunt     25000         BOS   Boston Celtics         20
85               Brook Lopez  21165675         BRK    Brooklyn Nets          1
86                Jeremy Lin  11483254         BRK    Brooklyn Nets          2
87             Trevor Booker   9250000         BRK    Brooklyn Nets          3
88          Andrew Nicholson   6088993         BRK    Brooklyn Nets          4
89            Deron Williams   5500000         BRK    Brooklyn Nets          5
9             Lucas Nogueira   1921320         TOR  Toronto Raptors         10
90                Luis Scola   5000000         BRK    Brooklyn Nets          6
91           Greivis Vasquez   4347826         BRK    Brooklyn Nets          7
92            K.J. McDaniels   3333333         BRK    Brooklyn Nets          8
93           Justin Hamilton   3000000         BRK    Brooklyn Nets          9
94                Randy Foye   2500000         BRK    Brooklyn Nets         10
95                Quincy Acy   1914544         BRK    Brooklyn Nets         11
96              Caris LeVert   1562280         BRK    Brooklyn Nets         12
97   Rondae Hollis-Jefferson   1395600         BRK    Brooklyn Nets         13
98           Marcus Thornton   1315448         BRK    Brooklyn Nets         14
99          Isaiah Whitehead   1074145         BRK    Brooklyn Nets         15

[600 rows x 5 columns]

In [4]:
# grab all NBA players' info using nba_py.player module

players = player.PlayerList(only_current=0)
players = players.info()
players

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,GAMES_PLAYED_FLAG
0,76001,"Abdelnaby, Alaa",Alaa Abdelnaby,0,1990,1994,HISTADD_alaa_abdelnaby,0,,,,,Y
1,76002,"Abdul-Aziz, Zaid",Zaid Abdul-Aziz,0,1968,1977,HISTADD_zaid_abdul-aziz,0,,,,,Y
2,76003,"Abdul-Jabbar, Kareem",Kareem Abdul-Jabbar,0,1969,1988,HISTADD_kareem_abdul-jabbar,0,,,,,Y
3,51,"Abdul-Rauf, Mahmoud",Mahmoud Abdul-Rauf,0,1990,2000,mahmoud_abdul-rauf,0,,,,,Y
4,1505,"Abdul-Wahad, Tariq",Tariq Abdul-Wahad,0,1997,2003,tariq_abdul-wahad,0,,,,,Y
5,949,"Abdur-Rahim, Shareef",Shareef Abdur-Rahim,0,1996,2007,shareef_abdur-rahim,0,,,,,Y
6,76005,"Abernethy, Tom",Tom Abernethy,0,1976,1980,HISTADD_tom_abernethy,0,,,,,Y
7,76006,"Able, Forest",Forest Able,0,1956,1956,HISTADD_frosty_able,0,,,,,Y
8,76007,"Abramovic, John",John Abramovic,0,1946,1947,HISTADD_brooms_abramovic,0,,,,,Y
9,203518,"Abrines, Alex",Alex Abrines,1,2016,2017,alex_abrines,1610612760,Oklahoma City,Thunder,OKC,thunder,Y
10,101165,"Acker, Alex",Alex Acker,0,2005,2008,alex_acker,0,,,,,Y
11,76008,"Ackerman, Donald",Donald Ackerman,0,1953,1953,HISTADD_buddy_ackerman,0,,,,,Y
12,76009,"Acres, Mark",Mark Acres,0,1987,1992,HISTADD_mark_acres,0,,,,,Y
13,76010,"Acton, Charles",Charles Acton,0,1967,1967,HISTADD_bud_acton,0,,,,,Y
14,203112,"Acy, Quincy",Quincy Acy,1,2012,2017,quincy_acy,1610612751,Brooklyn,Nets,BKN,nets,Y
15,76011,"Adams, Alvan",Alvan Adams,0,1975,1987,HISTADD_alvan_adams,0,,,,,Y
16,76012,"Adams, Don",Don Adams,0,1970,1976,HISTADD_don_adams,0,,,,,Y
17,200801,"Adams, Hassan",Hassan Adams,0,2006,2008,hassan_adams,0,,,,,Y
18,203919,"Adams, Jordan",Jordan Adams,0,2014,2015,jordan_adams,0,,,,,Y
19,149,"Adams, Michael",Michael Adams,0,1985,1995,michael_adams,0,,,,,Y
20,203500,"Adams, Steven",Steven Adams,1,2013,2017,steven_adams,1610612760,Oklahoma City,Thunder,OKC,thunder,Y
21,912,"Addison, Rafael",Rafael Addison,0,1986,1996,rafael_addison,0,,,,,Y
22,1628389,"Adebayo, Bam",Bam Adebayo,0,2017,2017,bam_adebayo,0,,,,,Y
23,76015,"Adelman, Rick",Rick Adelman,0,1968,1974,HISTADD_rick_adelman,0,,,,,Y
24,202399,"Adrien, Jeff",Jeff Adrien,0,2010,2014,jeff_adrien,0,,,,,Y
25,201167,"Afflalo, Arron",Arron Afflalo,1,2007,2017,arron_afflalo,1610612758,Sacramento,Kings,SAC,kings,Y
26,200772,"Ager, Maurice",Maurice Ager,0,2006,2010,maurice_ager,0,,,,,Y
27,76016,"Aguirre, Mark",Mark Aguirre,0,1981,1993,HISTADD_mark_aguirre,0,,,,,Y
28,201336,"Ahearn, Blake",Blake Ahearn,0,2007,2011,blake_ahearn,0,,,,,Y
29,76017,"Ainge, Danny",Danny Ainge,0,1981,1994,HISTADD_danny_ainge,0,,,,,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4231,203923,"Young, James",James Young,1,2014,2016,james_young,1610612738,Boston,Celtics,BOS,celtics,Y
4232,1626202,"Young, Joe",Joe Young,1,2015,2017,joe_young,1610612754,Indiana,Pacers,IND,pacers,Y
4233,1748,"Young, Korleone",Korleone Young,0,1998,1998,korleone_young,0,,,,,Y
4234,78634,"Young, Michael",Michael Young,0,1984,1989,HISTADD_michael_young,0,,,,,Y
4235,1628454,"Young, Mike",Mike Young,0,2017,2017,mike_young,0,,,,,Y
4236,201156,"Young, Nick",Nick Young,1,2007,2017,nick_young,1610612747,Los Angeles,Lakers,LAL,lakers,Y
4237,78635,"Young, Perry",Perry Young,0,1986,1986,HISTADD_perry_young,0,,,,,Y
4238,201970,"Young, Sam",Sam Young,0,2009,2012,sam_young,0,,,,,Y
4239,201152,"Young, Thaddeus",Thaddeus Young,1,2007,2017,thaddeus_young,1610612754,Indiana,Pacers,IND,pacers,Y
4240,1937,"Young, Tim",Tim Young,0,1999,1999,tim_young,0,,,,,Y
4241,78638,"Zaslofsky, Max",Max Zaslofsky,0,1946,1955,HISTADD_slats_zaslofsky,0,,,,,Y
4242,78639,"Zawoluk, Robert",Robert Zawoluk,0,1952,1954,HISTADD_zeke_zawoluk,0,,,,,Y
4243,203469,"Zeller, Cody",Cody Zeller,1,2013,2017,cody_zeller,1610612766,Charlotte,Hornets,CHA,hornets,Y
4244,78640,"Zeller, Dave",Dave Zeller,0,1961,1961,HISTADD_dave_zeller,0,,,,,Y
4245,78641,"Zeller, Gary",Gary Zeller,0,1970,1971,HISTADD_gary_zeller,0,,,,,Y
4246,78642,"Zeller, Hank",Hank Zeller,0,1946,1946,HISTADD_hank_zeller,0,,,,,Y
4247,202545,"Zeller, Luke",Luke Zeller,0,2012,2012,luke_zeller,0,,,,,Y
4248,203092,"Zeller, Tyler",Tyler Zeller,1,2012,2017,tyler_zeller,1610612738,Boston,Celtics,BOS,celtics,Y
4249,78643,"Zeno, Tony",Tony Zeno,0,1979,1979,HISTADD_tony_zeno,0,,,,,Y
4250,78644,"Zevenbergen, Phil",Phil Zevenbergen,0,1987,1987,HISTADD_phil_zevenbergen,0,,,,,Y
4251,1917,"Zhi-zhi, Wang",Wang Zhi-zhi,0,2000,2004,wang_zhi-zhi,0,,,,,Y
4252,678,"Zidek, George",George Zidek,0,1995,1997,george_zidek,0,,,,,Y
4253,2583,"Zimmerman, Derrick",Derrick Zimmerman,0,2005,2005,derrick_zimmerman,0,,,,,Y
4254,1627757,"Zimmerman, Stephen",Stephen Zimmerman,1,2016,2016,stephen_zimmerman,1610612753,Orlando,Magic,ORL,magic,Y
4255,1627835,"Zipser, Paul",Paul Zipser,1,2016,2017,paul_zipser,1610612741,Chicago,Bulls,CHI,bulls,Y
4256,1627790,"Zizic, Ante",Ante Zizic,0,2017,2017,ante_zizic,0,,,,,Y
4257,78647,"Zoet, Jim",Jim Zoet,0,1982,1982,HISTADD_jim_zoet,0,,,,,Y
4258,78648,"Zopf, Bill",Bill Zopf,0,1970,1970,HISTADD_zip_zopf,0,,,,,Y
4259,1627826,"Zubac, Ivica",Ivica Zubac,1,2016,2017,ivica_zubac,1610612747,Los Angeles,Lakers,LAL,lakers,Y
4260,78650,"Zunic, Matt",Matt Zunic,0,1948,1948,HISTADD_matt_zunic,0,,,,,Y

In [10]:
# List of all players in NBA history
player_strings = [x for x in players['DISPLAY_FIRST_LAST']]

# Series of players in 2016-2017
players_2016_2017 = total_df['player']

player_ids = []

for player in players_2016_2017:
    try:
        player_index = player_strings.index(player)
        player_id = players.iloc[player_index, 0]
        player_ids.append(player_id)
    except:
        player_ids.append("Player Not Found")
    
player_ids

[201942,
 202685,
 203998,
 203461,
 203925,
 203930,
 203915,
 101127,
 200745,
 1627812,
 203462,
 'Player Not Found',
 1626146,
 1626153,
 'Player Not Found',
 'Player Not Found',
 202331,
 201152,
 101145,
 2744,
 201952,
 201155,
 'Player Not Found',
 202362,
 1627783,
 202730,
 201166,
 1626167,
 202338,
 202379,
 1626202,
 1626176,
 299,
 1627777,
 202933,
 1626181,
 1627791,
 1627816,
 'Player Not Found',
 2548,
 202710,
 200765,
 201577,
 202703,
 201627,
 203487,
 1627832,
 1626166,
 1627756,
 203530,
 1626170,
 1626171,
 203477,
 1626245,
 1627835,
 'Player Not Found',
 'Player Not Found',
 'Player Not Found',
 203083,
 202699,
 202704,
 202720,
 1626246,
 203382,
 202397,
 2746,
 202694,
 203484,
 'Player Not Found',
 1626169,
 203493,
 1627740,
 2757,
 1627771,
 201189,
 'Player Not Found',
 203492,
 202328,
 203114,
 'Player Not Found',
 203089,
 203141,
 203521,
 201150,
 203953,
 203507,
 1627748,
 203503,
 202336,
 1626173,
 1627784,
 200779,
 1891,
 201563,
 1627763,
 203093,
 1626253,
 56,
 2544,
 201567,
 202681,
 2546,
 202684,
 'Player Not Found',
 202697,
 101112,
 2594,
 2210,
 2592,
 203895,
 1627770,
 202682,
 201960,
 201565,
 101114,
 101106,
 202336,
 2563,
 204002,
 2547,
 202355,
 201609,
 201961,
 201177,
 201149,
 204020,
 202682,
 2617,
 201949,
 203079,
 1626159,
 202337,
 203186,
 1626196,
 203585,
 201584,
 1627855,
 1627362,
 'Player Not Found',
 202728,
 1627875,
 200794,
 203145,
 101141,
 2399,
 2743,
 202498,
 200757,
 203471,
 1627098,
 'Player Not Found',
 896,
 101127,
 1627761,
 203488,
 204002,
 203527,
 201943,
 101181,
 203934,
 202390,
 1627856,
 203078,
 202322,
 101133,
 101162,
 202693,
 'Player Not Found',
 204001,
 201160,
 202711,
 203504,
 203107,
 'Player Not Found',
 201943,
 1626191,
 101110,
 1627849,
 'Player Not Found',
 203124,
 1627863,
 204067,
 202687,
 203095,
 201145,
 202696,
 203082,
 201571,
 201975,
 201228,
 1627851,
 203932,
 1626209,
 203901,
 'Player Not Found',
 204014,
 1627757,
 202620,
 1626148,
 1627875,
 1627868,
 200811,
 201587,
 203077,
 101107,
 202689,
 203087,
 201196,
 203469,
 1626163,
 2365,
 203148,
 2756,
 1626174,
 1626203,
 1626151,
 'Player Not Found',
 1627362,
 1627861,
 203492,
 201566,
 202683,
 201959,
 201586,
 1626195,
 203506,
 203518,
 202713,
 2555,
 203500,
 101179,
 203926,
 1627734,
 203460,
 203956,
 203200,
 203962,
 203924,
 203902,
 202708,
 202874,
 'Player Not Found',
 1627936,
 199,
 202330,
 202324,
 1626254,
 2207,
 202692,
 201588,
 2564,
 203957,
 202714,
 1626168,
 204060,
 203497,
 203918,
 1627850,
 203481,
 203526,
 1627762,
 1627779,
 'Player Not Found',
 203156,
 203081,
 203459,
 202323,
 203086,
 1627758,
 203090,
 202329,
 203105,
 202334,
 'Player Not Found',
 203943,
 2760,
 203994,
 203894,
 1626192,
 1626184,
 1627774,
 201568,
 202702,
 201163,
 201589,
 201579,
 2749,
 203115,
 2034,
 1626144,
 'Player Not Found',
 1627750,
 203486,
 2590,
 1627823,
 203914,
 1627736,
 203999,
 203910,
 202087,
 203133,
 101106,
 203950,
 'Player Not Found',
 202810,
 203489,
 201593,
 708,
 202332,
 203952,
 1626157,
 201941,
 201573,
 1627739,
 202357,
 201575,
 203498,
 203476,
 203897,
 203940,
 2755,
 1626145,
 101249,
 76993,
 202362,
 201956,
 2736,
 202389,
 203903,
 101181,
 201147,
 204028,
 201156,
 1626156,
 200768,
 201168,
 1627742,
 203944,
 203898,
 1897,
 1626204,
 203080,
 1627826,
 1626148,
 201146,
 1628021,
 200771,
 'Player Not Found',
 200752,
 201167,
 201936,
 201585,
 201229,
 202066,
 2440,
 201954,
 204038,
 201171,
 203463,
 1626161,
 1627741,
 1627834,
 1627781,
 201951,
 1627746,
 201961,
 2406,
 203934,
 1627732,
 'Player Not Found',
 200770,
 202339,
 202688,
 2199,
 201162,
 203096,
 203458,
 1627733,
 2571,
 203954,
 203118,
 1627737,
 1626164,
 'Player Not Found',
 203462,
 1627755,
 1626210,
 201563,
 'Player Not Found',
 203098,
 1626143,
 101179,
 204067,
 202407,
 201142,
 202691,
 203110,
 201939,
 2738,
 2733,
 2585,
 202353,
 2561,
 2760,
 201580,
 1626172,
 1627745,
 203546,
 203949,
 201574,
 1627775,
 2440,
 203917,
 202343,
 1627362,
 'Player Not Found',
 'Player Not Found',
 'Player Not Found',
 203515,
 201599,
 201933,
 2037,
 203085,
 203967,
 'Player Not Found',
 202325,
 1718,
 201601,
 101138,
 101109,
 201578,
 101187,
 1627744,
 2568,
 1626147,
 1627754,
 200770,
 203545,
 1717,
 203084,
 202083,
 101114,
 203939,
 203457,
 2734,
 202709,
 201619,
 200826,
 203552,
 203112,
 1626257,
 1626780,
 'Player Not Found',
 1627852,
 1627827,
 1626254,
 203539,
 1627789,
 1627812,
 202412,
 203510,
 'Player Not Found',
 1627784,
 1627791,
 1626188,
 'Player Not Found',
 203076,
 202326,
 1626158,
 201950,
 203524,
 201600,
 202734,
 201582,
 202347,
 201956,
 201967,
 202087,
 202362,
 203496,
 203093,
 202700,
 1627767,
 199,
 202348,
 203138,
 1626148,
 203462,
 101127,
 1626188,
 1882,
 1627782,
 1626253,
 201935,
 201583,
 201569,
 2772,
 'Player Not Found',
 1626273,
 203991,
 203143,
 204456,
 201628,
 1627778,
 56,
 1627819,
 1627786,
 'Player Not Found',
 203076,
 202326,
 201950,
 203524,
 203138,
 201600,
 202734,
 201582,
 202347,
 201956,
 201967,
 202087,
 202362,
 203093,
 202700,
 1626184,
 1627767,
 199,
 202348,
 203138,
 1626148,
 203462,
 101127,
 1626188,
 1627782,
 1626253,
 203464,
 200746,
 202695,
 2200,
 2225,
 1938,
 201980,
 201988,
 203473,
 1495,
 101135,
 1627848,
 203937,
 'Player Not Found',
 1627749,
 203613,
 201202,
 202722,
 1627854,
 1627879,
 1627868,
 1627853,
 202335,
 'Player Not Found',
 202712,
 202091,
 'Player Not Found',
 1627816,
 201143,
 101161,
 202340,
 203092,
 202738,
 'Player Not Found',
 203109,
 201973,
 1627759,
 203935,
 203482,
 1626179,
 203923,
 1627743,
 101123,
 1626175,
 1627751,
 'Player Not Found',
 1627791,
 'Player Not Found',
 1627883,
 1627875,
 201572,
 202391,
 202344,
 203094,
 101114,
 203512,
 2449,
 202349,
 'Player Not Found',
 203120,
 200751,
 203112,
 1627747,
 1626178,
 201977,
 1627785]

In [16]:
# append player IDs to total dataframe
# there are some "player not found" IDs due to differences name stylization between bball-reference and the NBA stats API

player_series = pd.Series(player_ids)
total_df["player_id"] = player_series
total_df = total_df.reset_index(drop=True)
total_df

,player,salary,team_abbrev,team_name,team_rank,player_id
0,DeMar DeRozan,26540100,TOR,Toronto Raptors,1,201942
1,Jonas Valanciunas,14382022,TOR,Toronto Raptors,2,202685
2,Bruno Caboclo,1589640,TOR,Toronto Raptors,11,203462
3,Anthony Bennett,1015696,BRK,Brooklyn Nets,16,202681
4,Joe Harris,980431,BRK,Brooklyn Nets,17,2546
5,Sean Kilpatrick,980431,BRK,Brooklyn Nets,18,202684
6,Spencer Dinwiddie,726672,BRK,Brooklyn Nets,19,Player Not Found
7,Jarrett Jack,500000,BRK,Brooklyn Nets,20,202697
8,Andrea Bargnani,323599,BRK,Brooklyn Nets,21,101112
9,Yogi Ferrell,202300,BRK,Brooklyn Nets,22,2594
10,Archie Goodwin,194494,BRK,Brooklyn Nets,23,2210
11,Egidijus Mockevicius,100000,BRK,Brooklyn Nets,24,2592
12,Cliff Alexander,51449,BRK,Brooklyn Nets,25,203895
13,Delon Wright,1577280,TOR,Toronto Raptors,12,Player Not Found
14,Beau Beech,45000,BRK,Brooklyn Nets,26,1627770
15,Prince Ibeh,31969,BRK,Brooklyn Nets,27,202682
16,Paul George,18314532,IND,Indiana Pacers,1,201960
17,Thaddeus Young,14153652,IND,Indiana Pacers,2,201565
18,Monta Ellis,10770000,IND,Indiana Pacers,3,101114
19,Al Jefferson,10230179,IND,Indiana Pacers,4,101106
20,Jeff Teague,8800000,IND,Indiana Pacers,5,202336
21,Rodney Stuckey,7000000,IND,Indiana Pacers,6,2563
22,C.J. Miles,4583450,IND,Indiana Pacers,7,204002
23,Lance Stephenson,4000000,IND,Indiana Pacers,8,2547
24,Pascal Siakam,1196040,TOR,Toronto Raptors,13,1626146
25,Lavoy Allen,4000000,IND,Indiana Pacers,9,202355
26,Aaron Brooks,2700000,IND,Indiana Pacers,10,201609
27,Myles Turner,2463840,IND,Indiana Pacers,11,201961
28,Kevin Seraphin,1800000,IND,Indiana Pacers,12,201177
29,Jeremy Evans,1227286,IND,Indiana Pacers,13,201149
...,...,...,...,...,...,...
570,Jaylen Brown,4743000,BOS,Boston Celtics,8,2757
571,Marcus Smart,3578880,BOS,Boston Celtics,9,1627771
572,Kelly Olynyk,3094014,BOS,Boston Celtics,10,201189
573,Terry Rozier,1906440,BOS,Boston Celtics,11,Player Not Found
574,James Young,1825200,BOS,Boston Celtics,12,203492
575,Demetrius Jackson,1450000,BOS,Boston Celtics,13,202328
576,Gerald Green,1410598,BOS,Boston Celtics,14,203114
577,Jordan Mickey,1223653,BOS,Boston Celtics,15,Player Not Found
578,Jakob Poeltl,2703960,TOR,Toronto Raptors,9,200745
579,R.J. Hunter,1200240,BOS,Boston Celtics,16,203089
580,Ben Bentil,250000,BOS,Boston Celtics,17,203141
581,Damion Lee,50000,BOS,Boston Celtics,18,203521
582,Jalen Jones,25000,BOS,Boston Celtics,19,201150
583,Marcus Georges-Hunt,25000,BOS,Boston Celtics,20,203953
584,Brook Lopez,21165675,BRK,Brooklyn Nets,1,203507
585,Jeremy Lin,11483254,BRK,Brooklyn Nets,2,1627748
586,Trevor Booker,9250000,BRK,Brooklyn Nets,3,203503
587,Andrew Nicholson,6088993,BRK,Brooklyn Nets,4,202336
588,Deron Williams,5500000,BRK,Brooklyn Nets,5,1626173
589,Lucas Nogueira,1921320,TOR,Toronto Raptors,10,1627812
590,Luis Scola,5000000,BRK,Brooklyn Nets,6,1627784
591,Greivis Vasquez,4347826,BRK,Brooklyn Nets,7,200779
592,K.J. McDaniels,3333333,BRK,Brooklyn Nets,8,1891
593,Justin Hamilton,3000000,BRK,Brooklyn Nets,9,201563
594,Randy Foye,2500000,BRK,Brooklyn Nets,10,1627763
595,Quincy Acy,1914544,BRK,Brooklyn Nets,11,203093
596,Caris LeVert,1562280,BRK,Brooklyn Nets,12,1626253
597,Rondae Hollis-Jefferson,1395600,BRK,Brooklyn Nets,13,56
598,Marcus Thornton,1315448,BRK,Brooklyn Nets,14,2544
599,Isaiah Whitehead,1074145,BRK,Brooklyn Nets,15,201567

In [17]:
# players with no IDs due to name storage differences

players_not_found = total_df.loc[total_df["player_id"] == "Player Not Found", :]
players_not_found

,player,salary,team_abbrev,team_name,team_rank,player_id
6,Spencer Dinwiddie,726672,BRK,Brooklyn Nets,19,Player Not Found
13,Delon Wright,1577280,TOR,Toronto Raptors,12,Player Not Found
44,Anthony Morrow,3488000,CHI,Chicago Bulls,6,Player Not Found
46,Fred VanVleet,543471,TOR,Toronto Raptors,15,Player Not Found
57,Brady Heslip,56500,TOR,Toronto Raptors,16,Player Not Found
58,Andre Drummond,22116750,DET,Detroit Pistons,1,Player Not Found
76,Ray McCallum,11949,DET,Detroit Pistons,18,Player Not Found
83,Spencer Hawes,6348759,MIL,Milwaukee Bucks,6,Player Not Found
88,Larry Sanders,1865547,MIL,Milwaukee Bucks,11,Player Not Found
106,Kyle Korver,5239437,CLE,Cleveland Cavaliers,8,Player Not Found
131,Luke Babbitt,1227000,MIA,Miami Heat,12,Player Not Found
135,Courtney Lee,11242000,NYK,New York Knicks,4,Player Not Found
159,Lamar Patterson,128623,ATL,Atlanta Hawks,17,Player Not Found
182,Bismack Biyombo,17000000,ORL,Orlando Magic,1,Player Not Found
194,C.J. Wilcox,1209680,ORL,Orlando Magic,12,Player Not Found
213,Christian Wood,874636,CHO,Charlotte Hornets,11,Player Not Found
228,Nick Collison,3750000,OKC,Oklahoma City Thunder,7,Player Not Found
276,Jusuf Nurkic,1921320,POR,Portland Trail Blazers,12,Player Not Found
300,Robbie Hummel,150000,DEN,Denver Nuggets,19,Player Not Found
312,Jerryd Bayless,9424084,PHI,Philadelphia 76ers,2,Player Not Found
316,Shabazz Muhammad,3046299,MIN,Minnesota Timberwolves,10,Player Not Found
321,Tyus Jones,1339680,MIN,Minnesota Timberwolves,15,Player Not Found
352,Anthony Tolliver,8000000,SAC,Sacramento Kings,5,Player Not Found
353,Garrett Temple,8000000,SAC,Sacramento Kings,6,Player Not Found
354,Matt Barnes,6125000,SAC,Sacramento Kings,7,Player Not Found
362,Malachi Richardson,1439880,SAC,Sacramento Kings,14,Player Not Found
393,Elijah Millsap,23069,PHO,Phoenix Suns,21,Player Not Found
403,Anderson Varejao,1551659,GSW,Golden State Warriors,9,Player Not Found
407,Ian Clark,1015696,GSW,Golden State Warriors,13,Player Not Found
442,Dwight Powell,8375000,DAL,Dallas Mavericks,5,Player Not Found
454,Dorian Finney-Smith,543471,DAL,Dallas Mavericks,15,Player Not Found
498,Marcelo Huertas,1500000,HOU,Houston Rockets,6,Player Not Found
501,T.J. McConnell,874636,PHI,Philadelphia 76ers,19,Player Not Found
509,DeMarcus Cousins,16957900,NOP,New Orleans Pelicans,2,Player Not Found
512,Hollis Thompson,442126,PHI,Philadelphia 76ers,20,Player Not Found
513,Omer Asik,9904494,NOP,New Orleans Pelicans,5,Player Not Found
520,Lance Stephenson,1227286,NOP,New Orleans Pelicans,12,Player Not Found
523,Chasson Randle,297311,PHI,Philadelphia 76ers,21,Player Not Found
533,Axel Toupane,20580,NOP,New Orleans Pelicans,24,Player Not Found
536,Kawhi Leonard,17638063,SAS,San Antonio Spurs,2,Player Not Found
548,Dejounte Murray,1180080,SAS,San Antonio Spurs,13,Player Not Found
565,Tyler Zeller,8000000,BOS,Boston Celtics,4,Player Not Found
573,Terry Rozier,1906440,BOS,Boston Celtics,11,Player Not Found
577,Jordan Mickey,1223653,BOS,Boston Celtics,15,Player Not Found

In [42]:
names_id_df = total_df[["player", "player_id"]]
names_id_df

needed_stats = ["GP", "W", "L", "W_PCT", "MIN", "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT", "FTM", "FTA", "FT_PCT", "OREB", "DREB", "REB", "AST", "TOV", "STL", "BLK", "PF", "PTS", "PLUS_MINUS"]

# Create stats df, and then merge

splits = player.PlayerYearOverYearSplits(names_id_df.iloc[0,1]).by_year()
total_stats = splits.loc[splits["GROUP_VALUE"] == "2016-17", needed_stats]
total_stats["player_id"] = names_id_df.iloc[0,1]
total_stats

,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,...,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS,player_id
1,74,47,27,0.635,35.4,9.7,20.9,0.467,0.4,1.7,...,4.3,5.2,3.9,2.4,1.1,0.2,1.8,27.3,2.0,201942

In [ ]:
for row in names_id_df.iterrows():
    player_id = row[1][1]
    if player_id == names_id_df.iloc[0,1]:
        continue
    if player_id == "Player Not Found":
        continue
    try:
        player_splits = player.PlayerYearOverYearSplits(player_id).by_year()
        player_stats = player_splits.loc[splits["GROUP_VALUE"] == "2016-17", needed_stats]
        player_stats["player_id"] = player_id
        total_stats = total_stats.append(player_stats)
    except:
        continue
    
merged_df = pd.merge(total_df, total_stats, how="left", on="player_id")
merged_df